name: Waypoint
version: '1.0-SNAPSHOT'
main: me.licurtis.waypoint.Waypoint
api-version: '1.21'
authors: [ courteous_ly ]
commands:
  waypoint:
    description: Save waypoints!
    usage: /<command> [get|save|delete]
